# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "centos7" do |centos7|

    centos7.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
      #v.gui = true
    end

    centos7.vm.box = "centos/7"
    centos7.vm.network "private_network", ip: "192.168.10.2"
    centos7.vm.hostname = "centos7-dev"
    centos7.vm.boot_timeout = 600
  end

  config.vm.define "laptop14" do |laptop14|

    laptop14.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      #v.gui = true
    end

    laptop14.vm.box = "ubuntu/trusty64"
    laptop14.vm.network "private_network", ip: "192.168.10.3"
    laptop14.vm.hostname = "Dell-Inspiron"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/roots/", "/srv/salt/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/pillar/", "/srv/pillar/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/ansible/", "/srv/ansible/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/bin/", "/srv/bin/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/test/", "/srv/test/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/puppet-lab/modules/", "/srv/puppet/"
    laptop14.vm.synced_folder "/Users/wicksy/git/wicksy/docker-lab", "/srv/docker-lab/"
  end

  config.vm.define "laptop16" do |laptop16|

    laptop16.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      #v.gui = true
    end

    laptop16.vm.box = "ubuntu/xenial64"
    laptop16.vm.network "private_network", ip: "192.168.10.4"
    laptop16.vm.hostname = "Dell-Inspiron"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/roots/", "/srv/salt/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/pillar/", "/srv/pillar/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/ansible/", "/srv/ansible/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/bin/", "/srv/bin/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/test/", "/srv/test/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/puppet-lab/modules/", "/srv/puppet/"
    laptop16.vm.synced_folder "/Users/wicksy/git/wicksy/docker-lab", "/srv/docker-lab/"
  end

  config.vm.define "pfsense" do |pfsense|

    pfsense.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
      #v.gui = true
    end

    pfsense.vm.box = "pfsense"
    pfsense.vm.network "private_network", ip: "192.168.10.100"
    pfsense.vm.hostname = "pfsense-dev"
    pfsense.vm.synced_folder '.', '/vagrant', disabled: true
    pfsense.ssh.shell = "/bin/sh"
    pfsense.vm.boot_timeout = 600
  end

  config.vm.define "mint" do |mint|

    mint.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      v.gui = true
    end

    mint.vm.box = "npalm/mint17-amd64-cinnamon"
    mint.vm.network "private_network", ip: "192.168.10.5"
    mint.vm.hostname = "Minty-Fresh"
    mint.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/roots/", "/srv/salt/"
    mint.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/pillar/", "/srv/pillar/"
    mint.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/ansible/", "/srv/ansible/"
    mint.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/bin/", "/srv/bin/"
    mint.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/test/", "/srv/test/"
    mint.vm.synced_folder "/Users/wicksy/Video/", "/home/vagrant/Downloads/"
  end

  config.vm.define "laptop18" do |laptop18|

    laptop18.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      #v.gui = true
    end

    laptop18.vm.box = "ubuntu/bionic64"
    laptop18.vm.network "private_network", ip: "192.168.10.6"
    laptop18.vm.hostname = "Dell-Inspiron"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/roots/", "/srv/salt/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/salt/pillar/", "/srv/pillar/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/ansible/", "/srv/ansible/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/bin/", "/srv/bin/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/laptop-build/test/", "/srv/test/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/puppet-lab/modules/", "/srv/puppet/"
    laptop18.vm.synced_folder "/Users/wicksy/git/wicksy/docker-lab", "/srv/docker-lab/"
  end

end
